# Platform
snd-soc-lpass-cpu-objs := lpass-cpu.o
snd-soc-lpass-platform-objs := lpass-platform.o

obj-$(CONFIG_SND_SOC_LPASS_CPU) += snd-soc-lpass-cpu.o
obj-$(CONFIG_SND_SOC_LPASS_PLATFORM) += snd-soc-lpass-platform.o

# Machine
snd-soc-ipq806x-max98357a-objs := ipq806x-max98357a.o

obj-$(CONFIG_SND_SOC_IPQ806X_MAX98357A) += snd-soc-ipq806x-max98357a.o
