# Platform
snd-soc-lpass-pcm-mi2s-objs := lpass-pcm-mi2s.o
snd-soc-lpass-cpu-mi2s-objs := lpass-cpu-mi2s.o

obj-$(CONFIG_SND_SOC_PCM_MI2S) += snd-soc-lpass-pcm-mi2s.o
obj-$(CONFIG_SND_SOC_CPU_MI2S) += snd-soc-lpass-cpu-mi2s.o

# Machine
snd-soc-ipq806x-objs := ipq806x.o

obj-$(CONFIG_SND_SOC_IPQ806X) += snd-soc-ipq806x.o
