#
# Makefile for linux/drivers/platform
#
obj-$(CONFIG_ARM)		+= arm/
obj-$(CONFIG_X86)		+= x86/
obj-$(CONFIG_OLPC)		+= olpc/
obj-$(CONFIG_GOLDFISH)		+= goldfish/
obj-$(CONFIG_CHROME_PLATFORMS)	+= chrome/
obj-$(CONFIG_CHROMEOS)		+= chromeos.o
obj-$(CONFIG_CHROMEOS_VBC_BLK)	+= chromeos_vbc_blk.o
obj-$(CONFIG_CHROMEOS_VBC_EC)	+= chromeos_vbc_ec.o
