#!/bin/bash

family=chromeos

flavourconf=$(find ${family} -name config.flavour.$1)
if [ ! -f "${flavourconf}" ]; then
    echo "Found no flavour configuration for '$1'." 1>&2
    exit 1
fi

archconfdir=$(dirname ${flavourconf})

# Generate .config
cat ${family}/config/config.common.${family} \
    ${archconfdir}/config.common.* \
    ${flavourconf} > .config
