obj-$(CONFIG_ARCH_ROCKCHIP) += rockchip.o efuse.o
obj-$(CONFIG_PM_GENERIC_DOMAINS) += pm_domains.o
obj-$(CONFIG_PM_SLEEP) += pm.o rk3288_ddr_suspend.o
obj-$(CONFIG_SMP) += headsmp.o platsmp.o
obj-y += call_with_mmu_disabled.o

obj-y += embedded/
