obj-y := dma-buf.o dma-fence.o dma-fence-array.o reservation.o seqno-fence.o
obj-$(CONFIG_DMABUF_CACHE)	+= dma-buf-cache.o
obj-$(CONFIG_DMABUF_PAGE_POOL)	+= dmabuf_page_pool.o
obj-$(CONFIG_SYNC_FILE)		+= sync_file.o
obj-$(CONFIG_SW_SYNC)		+= sw_sync.o sync_debug.o
