
obj-$(CONFIG_VIDEO_RK_CIF_CIF10) += video_cif_cif10.o
video_cif_cif10-objs += cif_cif10.o cif_cif10_img_src.o cif_cif10_img_src_v4l2-subdev.o cif_cif10_pltfrm.o cif_cif10_rv1108.o cif_cif10_v4l2.o

obj-$(CONFIG_VIDEO_CVBSIN) += cif_cvbsin.o cif_cvbsin_rv1108.o
obj-$(CONFIG_VIDEO_CIF1TO4) += cif_cif1to4.o
obj-$(CONFIG_VIDEO_NVP6124) += nvp6124/
