#
# Makefile for the Atheros network device drivers.
#

obj-$(CONFIG_ATL1) += atlx/
obj-$(CONFIG_ATL2) += atlx/
obj-$(CONFIG_ATL1E) += atl1e/
obj-$(CONFIG_ATL1C) += atl1c/
obj-$(CONFIG_ALX) += alx/
obj-$(CONFIG_QCA_NSS_DRV) += nss-drv/
obj-$(CONFIG_QCA_NSS_GMAC) += nss-gmac/
obj-$(CONFIG_QCA8337_LITE) += qca8337-lite/
