#ifndef _DT_BINDINGS_PINCTRL_TEGRA_XUSB_H
#define _DT_BINDINGS_PINCTRL_TEGRA_XUSB_H 1

#define TEGRA_XUSB_PADCTL_PCIE 0
#define TEGRA_XUSB_PADCTL_SATA 1
#define TEGRA_XUSB_PADCTL_USB3_P0 2
#define TEGRA_XUSB_PADCTL_USB3_P1 3
#define TEGRA_XUSB_PADCTL_UTMI_P0 4
#define TEGRA_XUSB_PADCTL_UTMI_P1 5
#define TEGRA_XUSB_PADCTL_UTMI_P2 6
#define TEGRA_XUSB_PADCTL_HSIC_P0 7
#define TEGRA_XUSB_PADCTL_HSIC_P1 8

#define TEGRA_XUSB_PADCTL_PIN_OTG_0   0
#define TEGRA_XUSB_PADCTL_PIN_OTG_1   1
#define TEGRA_XUSB_PADCTL_PIN_OTG_2   2
#define TEGRA_XUSB_PADCTL_PIN_ULPI_0  3
#define TEGRA_XUSB_PADCTL_PIN_HSIC_0  4
#define TEGRA_XUSB_PADCTL_PIN_HSIC_1  5
#define TEGRA_XUSB_PADCTL_PIN_PCIE_0  6
#define TEGRA_XUSB_PADCTL_PIN_PCIE_1  7
#define TEGRA_XUSB_PADCTL_PIN_PCIE_2  8
#define TEGRA_XUSB_PADCTL_PIN_PCIE_3  9
#define TEGRA_XUSB_PADCTL_PIN_PCIE_4 10
#define TEGRA_XUSB_PADCTL_PIN_SATA_0 11

#endif /* _DT_BINDINGS_PINCTRL_TEGRA_XUSB_H */
