
obj-$(CONFIG_VIDEO_RK_CIF_ISP11) += video_cif_isp11.o
video_cif_isp11-objs += cif_isp11.o cif_isp11_img_src.o cif_isp11_img_src_v4l2-subdev.o cif_isp11_isp.o cif_isp11_pltfrm.o cif_isp11_rk1108.o cif_isp11_v4l2.o