memc-of-y := memconsole-of.o memconsole.o
memc-x86-y := memconsole-x86.o memconsole.o

obj-$(CONFIG_GOOGLE_SMI)		+= gsmi.o
obj-$(CONFIG_GOOGLE_MEMCONSOLE_OF)	+= memc-of.o
obj-$(CONFIG_GOOGLE_MEMCONSOLE_X86)	+= memc-x86.o
