obj-$(CONFIG_AXD) := axd.o

axd-objs = axd_buffers.o \
	   axd_cmds.o \
	   axd_cmds_codec_internal.o \
	   axd_cmds_config.o \
	   axd_cmds_decoder_config.o \
	   axd_cmds_encoder_config.o \
	   axd_cmds_info.o \
	   axd_cmds_internal.o \
	   axd_cmds_pipes.o \
	   axd_hdr.o \
	   axd_module.o \
	   axd_platform_mips.o \
	   axd_sysfs_ctrl.o \
	   axd_sysfs_input.o \
	   axd_sysfs_output.o
