obj-$(CONFIG_ARCH_TEGRA) += fuse/

obj-$(CONFIG_ARCH_TEGRA) += common.o
obj-$(CONFIG_ARCH_TEGRA) += flowctrl.o
obj-$(CONFIG_ARCH_TEGRA) += pmc.o

obj-$(CONFIG_ARCH_TEGRA_132_SOC) += tegra132-trampoline.o
obj-$(CONFIG_ARCH_TEGRA_132_SOC) += pm-tegra132.o
