#ifndef __IWL_CHROME_CONFIG
#define __IWL_CHROME_CONFIG
/* This must match the CPTCFG_* symbols defined in the Makefile */
#define CPTCFG_MAC80211_MODULE 1
#define CPTCFG_MAC80211_LEDS 1
#define CPTCFG_MAC80211_RC_DEFAULT ""
#define CPTCFG_IWLWIFI_MODULE 1
#define CPTCFG_IWLMVM_MODULE 1
#define CPTCFG_IWLWIFI_OPMODE_MODULAR 1
#define CPTCFG_IWLWIFI_PCIE 1
#define CPTCFG_IWLWIFI_DEBUG 1
#define CPTCFG_IWLWIFI_NUM_CHANNELS 1
#define CPTCFG_IWLWIFI_SUPPORT_DEBUG_OVERRIDES 1

#ifdef CONFIG_IWL7000_DEBUGFS
#define CPTCFG_MAC80211_DEBUGFS 1
#define CPTCFG_IWLWIFI_DEBUGFS 1
#endif

#ifdef CONFIG_IWL7000_TRACING
#define CPTCFG_MAC80211_MESSAGE_TRACING 1
#define CPTCFG_IWLWIFI_DEVICE_TRACING 1
#endif

#ifdef CONFIG_IWL7000_TESTMODE
#define CPTCFG_IWLWIFI_DEVICE_TESTMODE 1
#define CPTCFG_NL80211_TESTMODE 1
#endif

#ifdef CONFIG_IWL7000_XVT_MODULE
#define CPTCFG_IWLXVT_MODULE 1
#endif

#define CPTCFG_IWLMVM_POWER_SCHEME 2

#endif
