#
# Makefile for triggers not associated with iio-devices
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_IIO_INTERRUPT_TRIGGER) += iio-trig-interrupt.o
obj-$(CONFIG_IIO_SYSFS_TRIGGER) += iio-trig-sysfs.o
obj-$(CONFIG_IIO_TRIGGER_HRTIMER) += iio-trig-hrtimer.o
