# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Rockchip Electronics Co., Ltd
#
# Makefile for Bosch ICM40605 IMU
#
obj-$(CONFIG_ICM40605) += icm40605.o
icm40605-objs := icm40605_core.o icm40605_trigger.o icm40605_ring.o
obj-$(CONFIG_ICM40605_I2C) += icm40605_i2c.o
obj-$(CONFIG_ICM40605_SPI) += icm40605_spi.o
