/*
 * drivers/media/i2c/soc_camera/xgold/s5k4h8.c
 *
 * s5k4h8 sensor driver
 *
 * Copyright (C) 2016 Fuzhou Rockchip Electronics Co., Ltd.
 *
 * Copyright (C) 2012-2014 Intel Mobile Communications GmbH
 *
 * Copyright (C) 2008 Texas Instruments.
 *
 * This file is licensed under the terms of the GNU General Public License
 * version 2. This program is licensed "as is" without any warranty of any
 * kind, whether express or implied.
 *
 * Note:
 *    07/01/2014: new implementation using v4l2-subdev
 *                        instead of v4l2-int-device.
 */

#include <linux/i2c.h>
#include <linux/io.h>
#include <linux/delay.h>
#include <linux/module.h>
#include <media/v4l2-subdev.h>
#include <media/videobuf-core.h>
#include <linux/slab.h>
#include "samsung_camera_module.h"

#define s5k4h8_DRIVER_NAME "s5k4h8"

#define s5k4h8_FETCH_LSB_GAIN(VAL) (VAL & 0x00ff)
#define s5k4h8_FETCH_MSB_GAIN(VAL) ((VAL >> 8) & 0xff)
#define s5k4h8_AEC_PK_LONG_GAIN_HIGH_REG 0x0204	/* Bit 6-13 */
#define s5k4h8_AEC_PK_LONG_GAIN_LOW_REG	 0x0205	/* Bits 0 -5 */

#define s5k4h8_AEC_PK_LONG_FINE_EXPO_REG 0x0200
#define s5k4h8_AEC_PK_LONG_COARSE_EXPO_REG 0x0202

#define s5k4h8_FETCH_3RD_BYTE_EXP(VAL) ((VAL >> 16) & 0xF)	/* 4 Bits */
#define s5k4h8_FETCH_2ND_BYTE_EXP(VAL) ((VAL >> 8) & 0xFF)	/* 8 Bits */
#define s5k4h8_FETCH_1ST_BYTE_EXP(VAL) (VAL & 0xFF)	/* 8 Bits */

#define s5k4h8_PIDH_ADDR 0x0000
#define s5k4h8_PIDL_ADDR 0x0001

#define s5k4h8_TIMING_VTS_REG 0x0340
#define s5k4h8_TIMING_HTS_REG 0x0342
#define s5k4h8_INTEGRATION_TIME_MARGIN 8
#define s5k4h8_FINE_INTG_TIME_MIN 0
#define s5k4h8_FINE_INTG_TIME_MAX_MARGIN 0
#define s5k4h8_COARSE_INTG_TIME_MIN 16
#define s5k4h8_COARSE_INTG_TIME_MAX_MARGIN 4
#define s5k4h8_TIMING_X_INC 0x0383
#define s5k4h8_TIMING_Y_INC 0x0387
#define s5k4h8_HORIZONTAL_START_REG 0x0344
#define s5k4h8_VERTICAL_START_REG 0x0346
#define s5k4h8_HORIZONTAL_END_REG 0x0348
#define s5k4h8_VERTICAL_END_REG 0x034A

#define s5k4h8_HORIZONTAL_END_REG 0x0348
#define s5k4h8_VERTICAL_HIGH_REG 0x034a
#define s5k4h8_HORIZONTAL_OUTPUT_SIZE_REG 0x034c
#define s5k4h8_VERTICAL_OUTPUT_SIZE_REG 0x380e
#define s5k4h8_FLIP_REG 0x0101
#define s5k4h8_MIRROR_REG 0x0101

#define s5k4h8_EXT_CLK 26000000

#define s5k4h8_FULL_SIZE_RESOLUTION_WIDTH 3264
#define s5k4h8_BINING_SIZE_RESOLUTION_WIDTH 1632
#define s5k4h8_VIDEO_SIZE_RESOLUTION_WIDTH 3200

#define s5k4h8_MODE_SELECT (0x0100)
#define s5k4h8_MODE_SELECT_OFF (0x00U)
#define s5k4h8_MODE_SELECT_ON (0x01U)

#define s5k4h8_EXP_VALID_FRAMES 4
/* High byte of product ID */
#define s5k4h8_PIDH_MAGIC 0x40
/* Low byte of product ID  */
#define s5k4h8_PIDL_MAGIC 0x88

#define BG_Ratio_Typical  0x129
#define RG_Ratio_Typical  0x11f
#define GAIN_DEFAULT       0x0100

struct s5k4h8_otp_struct {
	int otp_en;
	int flag;
	int module_integrator_id;
	int production_year;
	int production_month;
	int production_day;
	int rg_ratio;
	int bg_ratio;
	int lenc[240];
	int checksum;
	int VCM_start;
	int VCM_end;
	int VCM_dir;
	int R_gain;
	int G_gain;
	int B_gain;
};


static struct s5k4h8_otp_struct *otp_ptr;
static struct samsung_camera_module s5k4h8;
static struct samsung_camera_module_custom_config s5k4h8_custom_config;

/* ======================================================================== */
/* Base sensor configs */
/* ======================================================================== */

/* MCLK:24MHz  3264x2448  18fps   mipi 4lane   480Mbps/lane */
static struct samsung_camera_module_reg s5k4h8_init_tab_3264_2448_30fps[] = {
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6028, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x1FD0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0448},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0349},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0160},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC26A},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x511A},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x8180},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x60B8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x20E8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x13A0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x38B5},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0021},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0446},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x8DF8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0010},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F5},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xB470},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0122},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6946},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x59F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x9DF8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xFF28},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x05D0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0020},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x08B1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x04F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6914},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2046},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x38BD},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0120},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF8E7},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x10B5},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x92B0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0C46},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4822},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6946},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x46F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0020},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6946},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x04EB},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4003},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0A5C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x02F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0F02},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x04F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1020},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0A5C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x401C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1209},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x5A70},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4828},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF2D3},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x12B0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x10BD},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2DE9},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF041},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x164E},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0F46},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x06F1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1105},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xA236},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xB0B1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1449},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1248},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0968},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0078},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xB1F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6A10},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC007},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0ED0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0846},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xFFF7},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xBEFF},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x84B2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2946},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2046},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xFFF7},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xD0FF},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4FF4},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x9072},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x3146},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x04F1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4800},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x16F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x002F},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x05D0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x3146},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2846},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xBDE8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF041},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x13B8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xBDE8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF081},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0022},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xAFF2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x5501},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0348},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x10B8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0C40},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0560},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x152D},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x48F6},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x296C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC0F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x000C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6047},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x41F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x950C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC0F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x000C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6047},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x49F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x514C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC0F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x000C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6047},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4088},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0166},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0002},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x5360, 0x0004},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x3078, 0x0059},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x307C, 0x0025},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x36D0, 0x00DD},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x36D2, 0x0100},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x306A, 0x00EF},

	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6028, 0x4000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x6214},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x7971},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x6218},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x7150},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6028, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x0EC6},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xFCFC, 0x4000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF490, 0x0030},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF47A, 0x0012},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF428, 0x0200},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF48E, 0x0010},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF45C, 0x0004},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0B04, 0x0101},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0B00, 0x0080},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6028, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x0C40},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0140},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xFCFC, 0x4000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0200, 0x0618},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0202, 0x0465},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x31AA, 0x0004},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x1006, 0x0006},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x31FA, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x020E, 0x0100},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0344, 0x0008},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0348, 0x0CC7},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0346, 0x0008},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x034A, 0x0997},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x034C, 0x0CC0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x034E, 0x0990},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0342, 0x0EA0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0340, 0x09BC},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0900, 0x0111},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0380, 0x0001},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0382, 0x0001},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0384, 0x0001},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0386, 0x0001},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0400, 0x0002},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0404, 0x0010},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0114, 0x0330},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0136, 0x1800},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0300, 0x0005},

	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0302, 0x0001},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0304, 0x0006},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0306, 0x008C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x030C, 0x0006},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x030E, 0x008C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x3008, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA, 0x0103, 0x1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0100, 0x0},
};

static const struct samsung_camera_module_reg s5k4h8_init_tab_1632_1224_30fps[] = {
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6028, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x1FD0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0448},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0349},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0160},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC26A},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x511A},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x8180},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x60B8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x20E8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x13A0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x38B5},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0021},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0446},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x8DF8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0010},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F5},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xB470},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0122},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6946},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x59F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x9DF8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xFF28},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x05D0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0020},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x08B1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x04F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6914},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2046},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x38BD},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0120},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF8E7},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x10B5},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x92B0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0C46},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4822},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6946},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x46F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0020},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6946},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x04EB},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4003},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0A5C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x02F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0F02},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x04F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1020},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0A5C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x401C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1209},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x5A70},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4828},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF2D3},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x12B0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x10BD},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2DE9},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF041},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x164E},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0F46},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x06F1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1105},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xA236},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xB0B1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1449},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x1248},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0968},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0078},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xB1F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6A10},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC007},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0ED0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0846},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xFFF7},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xBEFF},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x84B2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2946},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2046},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xFFF7},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xD0FF},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4FF4},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x9072},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x3146},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x04F1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4800},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x16F8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x002F},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x05D0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x3146},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2846},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xBDE8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF041},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x13B8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xBDE8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xF081},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0022},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xAFF2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x5501},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0348},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x00F0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x10B8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0C40},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0560},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x152D},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x48F6},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x296C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC0F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x000C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6047},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x41F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x950C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC0F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x000C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6047},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x49F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x514C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0xC0F2},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x000C},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x6047},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x4088},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0166},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0002},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x5360, 0x0004},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x3078, 0x0059},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x307C, 0x0025},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x36D0, 0x00DD},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x36D2, 0x0100},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x306A, 0x00EF},

	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6028, 0x4000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x6214},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x7971},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x6218},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x7150},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6028, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x0EC6},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xFCFC, 0x4000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF490, 0x0030},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF47A, 0x0012},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF428, 0x0200},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF48E, 0x0010},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xF45C, 0x0004},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0B04, 0x0101},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0B00, 0x0080},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6028, 0x2000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x602A, 0x0C40},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x6F12, 0x0140},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0xFCFC, 0x4000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0200, 0x0800},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0202, 0x0465},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x31AA, 0x0004},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x1006, 0x0006},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x31FA, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x020E, 0x0100},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0344, 0x0008},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0348, 0x0CC7},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0346, 0x0008},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x034A, 0x0997},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x034C, 0x0660},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x034E, 0x04C8},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0342, 0x0EA0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0340, 0x04E0},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0900, 0x0212},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0380, 0x0001},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0382, 0x0001},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0384, 0x0001},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0386, 0x0003},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0400, 0x0002},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0404, 0x0020},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0114, 0x0330},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0136, 0x1800},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0300, 0x0005},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0302, 0x0002},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0304, 0x0004},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x0306, 0x0075},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x030C, 0x0006},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x030E, 0x0078},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA, 0x3008, 0x0000},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA, 0x0103, 0x1},
	{SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA, 0x0100, 0x0},
};

/* ======================================================================== */
static struct samsung_camera_module_config s5k4h8_configs[] = {
	{
		.name = "1632x1224_30fps",
		.frm_fmt = {
			.width = 1632,
			.height = 1224,
			.code = V4L2_MBUS_FMT_SGRBG10_1X10
		},
		.frm_intrvl = {
			.interval = {
				.numerator = 1,
				.denominator = 30
			}
		},
		.auto_exp_enabled = false,
		.auto_gain_enabled = false,
		.auto_wb_enabled = false,
		.reg_table = (void *)s5k4h8_init_tab_1632_1224_30fps,
		.reg_table_num_entries =
			sizeof(s5k4h8_init_tab_1632_1224_30fps)
			/
			sizeof(s5k4h8_init_tab_1632_1224_30fps[0]),
		.reg_diff_table = (void *)s5k4h8_init_tab_1632_1224_30fps,
		.reg_diff_table_num_entries =
			sizeof(s5k4h8_init_tab_1632_1224_30fps)
			/
			sizeof(s5k4h8_init_tab_1632_1224_30fps[0]),
		.v_blanking_time_us = 8693,
		PLTFRM_CAM_ITF_MIPI_CFG(0, 4, 480, s5k4h8_EXT_CLK)
	},
	{
		.name = "3264x2448_30fps",
		.frm_fmt = {
			.width = 3264,
			.height = 2448,
			.code = V4L2_MBUS_FMT_SGRBG10_1X10
		},
		.frm_intrvl = {
			.interval = {
				.numerator = 1,
				.denominator = 30
			}
		},
		.auto_exp_enabled = false,
		.auto_gain_enabled = false,
		.auto_wb_enabled = false,
		.reg_table = (void *)s5k4h8_init_tab_3264_2448_30fps,
		.reg_table_num_entries =
			sizeof(s5k4h8_init_tab_3264_2448_30fps)
			/
			sizeof(s5k4h8_init_tab_3264_2448_30fps[0]),
		.reg_diff_table = NULL,
		.reg_diff_table_num_entries = 0,
		.v_blanking_time_us = 7251,
		PLTFRM_CAM_ITF_MIPI_CFG(0, 4, 560, s5k4h8_EXT_CLK)
	}
};

/*--------------------------------------------------------------------------*/

static int s5k4h8_g_VTS(struct samsung_camera_module *cam_mod, u32 *vts)
{
	int ret;

	ret = samsung_camera_module_read_reg_table(
		cam_mod,
		s5k4h8_TIMING_VTS_REG,
		vts);
	if (IS_ERR_VALUE(ret))
		goto err;

	cam_mod->vts_cur = *vts;

	return 0;
err:
	samsung_camera_module_pr_err(cam_mod, "failed with error (%d)\n", ret);
	return ret;
}

/*--------------------------------------------------------------------------*/

static int s5k4h8_auto_adjust_fps(
	struct samsung_camera_module *cam_mod,
	u32 exp_time)
{
	int ret;
	u32 vts;

	if ((cam_mod->exp_config.exp_time + s5k4h8_COARSE_INTG_TIME_MAX_MARGIN)
		> cam_mod->vts_min)
		vts = cam_mod->exp_config.exp_time+
			s5k4h8_COARSE_INTG_TIME_MAX_MARGIN;
	else
		vts = cam_mod->vts_min;
	ret = samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
		s5k4h8_TIMING_VTS_REG,
		vts & 0xFFFF);

	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
					     "failed with error (%d)\n",
					     ret);
	} else {
		samsung_camera_module_pr_info(cam_mod,
					      "updated vts = %d,vts_min=%d\n",
					      vts, cam_mod->vts_min);
		cam_mod->vts_cur = vts;
	}

	return ret;
}

/*--------------------------------------------------------------------------*/

static int s5k4h8_set_vts(
	struct samsung_camera_module *cam_mod,
	u32 vts)
{
	int ret = 0;

	if (vts < cam_mod->vts_min)
		return ret;

	ret = samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
		s5k4h8_TIMING_VTS_REG,
		vts & 0xFFFF);

	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
					     "failed with error (%d)\n",
					     ret);
	} else {
		samsung_camera_module_pr_debug(cam_mod,
					       "updated vts = %d,vts_min=%d\n",
					       vts, cam_mod->vts_min);
		cam_mod->vts_cur = vts;
	}

	return ret;
}

/*--------------------------------------------------------------------------*/
static int s5k4h8_write_aec(struct samsung_camera_module *cam_mod)
{
	int ret = 0;

	samsung_camera_module_pr_debug(cam_mod,
				       "exp_time = %d, gain = %d, flash_mode = %d\n",
				       cam_mod->exp_config.exp_time,
				       cam_mod->exp_config.gain,
				       cam_mod->exp_config.flash_mode);

	/* if the sensor is already streaming, write to shadow registers,
		if the sensor is in SW standby, write to active registers,
		if the sensor is off/registers are not writeable, do nothing */
	if ((cam_mod->state == SAMSUNG_CAMERA_MODULE_SW_STANDBY) ||
		(cam_mod->state == SAMSUNG_CAMERA_MODULE_STREAMING)) {
		u32 a_gain = cam_mod->exp_config.gain;
		u32 exp_time = cam_mod->exp_config.exp_time;

		mutex_lock(&cam_mod->lock);
		a_gain = a_gain * cam_mod->exp_config.gain_percent / 100;

		if (!IS_ERR_VALUE(ret) && cam_mod->auto_adjust_fps)
			ret = s5k4h8_auto_adjust_fps(cam_mod,
						cam_mod->exp_config.exp_time);
		ret |= samsung_camera_module_write_reg(cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA,
			s5k4h8_AEC_PK_LONG_GAIN_HIGH_REG,
			s5k4h8_FETCH_MSB_GAIN(a_gain));
		ret |= samsung_camera_module_write_reg(cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA,
			s5k4h8_AEC_PK_LONG_GAIN_LOW_REG,
			s5k4h8_FETCH_LSB_GAIN(a_gain));
		ret |= samsung_camera_module_write_reg(cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
			s5k4h8_AEC_PK_LONG_COARSE_EXPO_REG,
			exp_time);
		if (!cam_mod->auto_adjust_fps)
			ret |= s5k4h8_set_vts(cam_mod, cam_mod->exp_config.vts_value);
		mutex_unlock(&cam_mod->lock);
	}

	if (IS_ERR_VALUE(ret))
		samsung_camera_module_pr_err(cam_mod,
			"failed with error (%d)\n", ret);
	return ret;
}

/*--------------------------------------------------------------------------*/

static int s5k4h8_g_ctrl(struct samsung_camera_module *cam_mod, u32 ctrl_id)
{
	int ret = 0;

	samsung_camera_module_pr_debug(cam_mod, "\n");

	switch (ctrl_id) {
	case V4L2_CID_GAIN:
	case V4L2_CID_EXPOSURE:
	case V4L2_CID_FLASH_LED_MODE:
		/* nothing to be done here */
		break;
	default:
		ret = -EINVAL;
		break;
	}

	if (IS_ERR_VALUE(ret))
		samsung_camera_module_pr_debug(cam_mod,
			"failed with error (%d)\n", ret);
	return ret;
}

/*--------------------------------------------------------------------------*/
static int s5k4h8_filltimings(struct samsung_camera_module_custom_config *custom)
{
	int i, j;
	struct samsung_camera_module_config *config;
	struct samsung_camera_module_timings *timings;
	struct samsung_camera_module_reg *reg_table;
	int reg_table_num_entries;

	for (i = 0; i < custom->num_configs; i++) {
		config = &custom->configs[i];
		reg_table = config->reg_table;
		reg_table_num_entries = config->reg_table_num_entries;
		timings = &config->timings;

		memset(timings, 0x00, sizeof(*timings));
		for (j = 0; j < reg_table_num_entries; j++) {
			switch (reg_table[j].reg) {
			case s5k4h8_TIMING_VTS_REG:
				timings->frame_length_lines =
					reg_table[j].val;
				break;
			case s5k4h8_TIMING_HTS_REG:
				timings->line_length_pck =
					reg_table[j].val;
				break;
			case s5k4h8_TIMING_X_INC:
				timings->binning_factor_x = ((reg_table[j].val >> 4) + 1) / 2;
				if (timings->binning_factor_x == 0)
					timings->binning_factor_x = 1;
				break;
			case s5k4h8_TIMING_Y_INC:
				timings->binning_factor_y = ((reg_table[j].val >> 4) + 1) / 2;
				if (timings->binning_factor_y == 0)
					timings->binning_factor_y = 1;
				break;
			case s5k4h8_HORIZONTAL_START_REG:
				timings->crop_horizontal_start =
					reg_table[j].val;
				break;
			case s5k4h8_VERTICAL_START_REG:
				timings->crop_vertical_start =
					reg_table[j].val;
				break;
			case s5k4h8_HORIZONTAL_END_REG:
				timings->crop_horizontal_end =
					reg_table[j].val;
				break;
			case s5k4h8_VERTICAL_END_REG:
				timings->crop_vertical_end =
					reg_table[j].val;
				break;
			case s5k4h8_HORIZONTAL_OUTPUT_SIZE_REG:
				timings->sensor_output_width =
					reg_table[j].val;
				break;
			case s5k4h8_VERTICAL_OUTPUT_SIZE_REG:
				timings->sensor_output_height =
					reg_table[j].val;
				break;
			case s5k4h8_AEC_PK_LONG_FINE_EXPO_REG:
				timings->exp_time =
					reg_table[j].val;
				break;
			case s5k4h8_AEC_PK_LONG_GAIN_LOW_REG:
				timings->gain =
					(reg_table[j].val | timings->gain);
				break;
			case s5k4h8_AEC_PK_LONG_GAIN_HIGH_REG:
				timings->gain =
					((reg_table[j].val << 8) |
					(timings->gain & 0xff));
				break;
			}
		}

		timings->exp_time >>= 4;
		timings->vt_pix_clk_freq_hz =
			config->frm_intrvl.interval.denominator
			* timings->frame_length_lines
			* timings->line_length_pck;

		timings->coarse_integration_time_min =
			s5k4h8_COARSE_INTG_TIME_MIN;
		timings->coarse_integration_time_max_margin =
			s5k4h8_COARSE_INTG_TIME_MAX_MARGIN;

		/* SAMSUNG Sensor do not use fine integration time. */
		timings->fine_integration_time_min =
			s5k4h8_FINE_INTG_TIME_MIN;
		timings->fine_integration_time_max_margin =
			s5k4h8_FINE_INTG_TIME_MAX_MARGIN;
	}

	return 0;
}
static int s5k4h8_g_timings(struct samsung_camera_module *cam_mod,
	struct samsung_camera_module_timings *timings)
{
	int ret = 0;
	unsigned int vts;

	if (IS_ERR_OR_NULL(cam_mod->active_config))
		goto err;

	*timings = cam_mod->active_config->timings;

	vts = (!cam_mod->vts_cur) ?
		timings->frame_length_lines :
		cam_mod->vts_cur;
	if (cam_mod->frm_intrvl_valid)
		timings->vt_pix_clk_freq_hz =
			cam_mod->frm_intrvl.interval.denominator
			* vts
			* timings->line_length_pck;
	else
		timings->vt_pix_clk_freq_hz =
			cam_mod->active_config->frm_intrvl.interval.denominator
			*vts
			* timings->line_length_pck;

	timings->frame_length_lines = vts;

	return ret;
err:
	samsung_camera_module_pr_err(cam_mod,
			"failed with error (%d)\n", ret);
	return ret;
}

/*--------------------------------------------------------------------------*/
#if 0
/* Reconfigure bayer order according to xml's definition */
static int s5k4h8_set_flip(
	struct samsung_camera_module *cam_mod,
	struct pltfrm_camera_module_reg reglist[],
	int len)
{
	int i, mode = 0;
	u16 match_reg[2];

	mode = samsung_camera_module_get_flip_mirror(cam_mod);
	if (mode == -1) {
		samsung_camera_module_pr_info(
			cam_mod,
			"dts don't set flip, return!\n");
		return 0;
	}

	if (!IS_ERR_OR_NULL(cam_mod->active_config)) {
		switch (cam_mod->active_config->frm_fmt.width) {
		case s5k4h8_FULL_SIZE_RESOLUTION_WIDTH:
			if (mode == SAMSUNG_FLIP_BIT_MASK) {
				match_reg[0] = 0x06;
				match_reg[1] = 0x40;
			} else if (mode == SAMSUNG_MIRROR_BIT_MASK) {
				match_reg[0] = 0x00;
				match_reg[1] = 0x46;
			} else if (mode == (SAMSUNG_MIRROR_BIT_MASK |
				SAMSUNG_FLIP_BIT_MASK)) {
				match_reg[0] = 0x06;
				match_reg[1] = 0x46;
			} else {
				match_reg[0] = 0x00;
				match_reg[1] = 0x40;
			}
			break;
		case s5k4h8_VIDEO_SIZE_RESOLUTION_WIDTH:
			if (mode == SAMSUNG_FLIP_BIT_MASK) {
				match_reg[0] = 0x06;
				match_reg[1] = 0x40;
			} else if (mode == SAMSUNG_MIRROR_BIT_MASK) {
				match_reg[0] = 0x00;
				match_reg[1] = 0x46;
			} else if (mode == (SAMSUNG_MIRROR_BIT_MASK |
				SAMSUNG_FLIP_BIT_MASK)) {
				match_reg[0] = 0x06;
				match_reg[1] = 0x46;
			} else {
				match_reg[0] = 0x00;
				match_reg[1] = 0x40;
			}
			break;
		case s5k4h8_BINING_SIZE_RESOLUTION_WIDTH:
			if (mode == SAMSUNG_FLIP_BIT_MASK) {
				match_reg[0] = 0x06;
				match_reg[1] = 0x61;
			} else if (mode == SAMSUNG_MIRROR_BIT_MASK) {
				match_reg[0] = 0x00;
				match_reg[1] = 0x67;
			} else if (mode == (SAMSUNG_MIRROR_BIT_MASK |
				SAMSUNG_FLIP_BIT_MASK)) {
				match_reg[0] = 0x06;
				match_reg[1] = 0x67;
			} else {
				match_reg[0] = 0x00;
				match_reg[1] = 0x61;
			}
			break;
		default:
				return 0;
		}

		for (i = len; i > 0; i--) {
			if (reglist[i].reg == s5k4h8_FLIP_REG)
				reglist[i].val = match_reg[0];
			else if (reglist[i].reg == s5k4h8_MIRROR_REG)
				reglist[i].val = match_reg[1];
		}
	}

	return 0;
}
#endif
/*--------------------------------------------------------------------------*/

static int s5k4h8_s_ctrl(struct samsung_camera_module *cam_mod, u32 ctrl_id)
{
	int ret = 0;

	samsung_camera_module_pr_debug(cam_mod, "\n");

	switch (ctrl_id) {
	case V4L2_CID_GAIN:
	case V4L2_CID_EXPOSURE:
		ret = s5k4h8_write_aec(cam_mod);
		break;
	case V4L2_CID_FLASH_LED_MODE:
		/* nothing to be done here */
		break;
	default:
		ret = -EINVAL;
		break;
	}

	if (IS_ERR_VALUE(ret))
		samsung_camera_module_pr_debug(cam_mod,
			"failed with error (%d) 0x%x\n", ret, ctrl_id);
	return ret;
}

/*--------------------------------------------------------------------------*/

static int s5k4h8_s_ext_ctrls(struct samsung_camera_module *cam_mod,
				 struct samsung_camera_module_ext_ctrls *ctrls)
{
	int ret = 0;

	/* Handles only exposure and gain together special case. */
	if (ctrls->ctrls[0].id == V4L2_CID_GAIN ||
	    ctrls->ctrls[0].id == V4L2_CID_EXPOSURE)
		ret = s5k4h8_write_aec(cam_mod);
	else
		ret = -EINVAL;

	if (IS_ERR_VALUE(ret))
		samsung_camera_module_pr_debug(cam_mod,
			"failed with error (%d)\n", ret);
	return ret;
}

/*--------------------------------------------------------------------------*/
int update_awb_gain(struct samsung_camera_module *cam_mod)
{
	u16 r_gain;
	u16 b_gain;
	u16 gr_gain;
	u16 gb_gain;
	u16 g_gain;
	int ret = 0;
	u16 r_ratio, b_ratio;

	r_ratio = 512 * (RG_Ratio_Typical) / (otp_ptr->rg_ratio);
	b_ratio = 512 * (BG_Ratio_Typical) / (otp_ptr->bg_ratio);

	if (!r_ratio || !b_ratio) {
		samsung_camera_module_pr_err(cam_mod, "rg ratio is zero!\n");
		return -1;
	}

	if (r_ratio >= 512) {
		if (b_ratio >= 512) {
			r_gain = (u16)(GAIN_DEFAULT * r_ratio / 512);
			g_gain = GAIN_DEFAULT;
			b_gain = (u16)(GAIN_DEFAULT * b_ratio / 512);
		} else {
			r_gain = (u16)(GAIN_DEFAULT * r_ratio / b_ratio);
			g_gain = (u16)(GAIN_DEFAULT * 512 / b_ratio);
			b_gain = GAIN_DEFAULT;
		}
	} else {
		if (b_ratio >= 512) {
			r_gain = GAIN_DEFAULT;
			g_gain = (u16)(GAIN_DEFAULT * 512 / r_ratio);
			b_gain = (u16)(GAIN_DEFAULT *  b_ratio / r_ratio);
		} else {
			gr_gain = (u16)(GAIN_DEFAULT * 512 / r_ratio);
			gb_gain = (u16)(GAIN_DEFAULT * 512 / b_ratio);

			if (gr_gain >= gb_gain)	{
				r_gain = GAIN_DEFAULT;
				g_gain = (u16)(GAIN_DEFAULT * 512 / r_ratio);
				b_gain = (u16)(GAIN_DEFAULT * b_ratio / r_ratio);
			} else {
				r_gain = (u16)(GAIN_DEFAULT * r_ratio / b_ratio);
				g_gain = (u16)(GAIN_DEFAULT * 512 / b_ratio);
				b_gain = GAIN_DEFAULT;
			}
		}
	}

	ret = samsung_camera_module_write_reg(
			cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
			0x6028, 0x4000);
	ret |= samsung_camera_module_write_reg(
			cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
			0x602a, 0x3058);
	ret |= samsung_camera_module_write_reg(
			cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
			0x602a, 0x3058);
	ret |= samsung_camera_module_write_reg(
			cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA,
			0x6f12, 0x01);
	ret |= samsung_camera_module_write_reg(
			cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
			0x020e, g_gain);
	ret |= samsung_camera_module_write_reg(
			cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
			0x0210, r_gain);
	ret |= samsung_camera_module_write_reg(
			cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
			0x0212, b_gain);
	ret |= samsung_camera_module_write_reg(
			cam_mod,
			SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
			0x0214, g_gain);
	if (IS_ERR_VALUE(ret))
		samsung_camera_module_pr_err(cam_mod, "otp awb gain apply failed\n");
	else
		samsung_camera_module_pr_info(cam_mod,
					"xuhf: s5k4h8_update:%s, rgain:%x ggain %x bgain %x\n",
					__func__, r_gain, g_gain, b_gain);

	return ret;
}

int update_lenc(struct samsung_camera_module *cam_mod)
{
	int ret = 0;

	return ret;
}
static int s5k4h8_start_streaming(struct samsung_camera_module *cam_mod)
{
	int ret = 0, temp = 0, i;

	samsung_camera_module_pr_info(cam_mod, "active config=%s\n", cam_mod->active_config->name);

	if (otp_ptr != NULL && otp_ptr->otp_en == 1 && cam_mod->update_config
	    && cam_mod->active_config->soft_reset) {
		samsung_camera_module_pr_info(cam_mod,
					"apply otp data...\n");
		update_awb_gain(cam_mod);
		update_lenc(cam_mod);
	}
	ret = s5k4h8_g_VTS(cam_mod, &cam_mod->vts_min);
	if (IS_ERR_VALUE(ret))
		goto err;
	/*
	cam_mod->exp_config.exp_time = 0x960*4;
	cam_mod->exp_config.gain = 256;
	cam_mod->exp_config.gain_percent = 100;
	ret = s5k4h8_write_aec(cam_mod);
	if (IS_ERR_VALUE(ret))
		goto err;
	*/

	mutex_lock(&cam_mod->lock);
	/* timing check */
	for (i = 0; i < 4; i++) {
		ret = samsung_camera_module_read_reg(cam_mod, 1, 0x0005, &temp);
		if (temp != 0xff)
			break;
		msleep(15);
		if (i == 4)
			samsung_camera_module_pr_err(cam_mod, "stream on state error\n");
	}

	if (IS_ERR_VALUE(samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA,
		s5k4h8_MODE_SELECT, s5k4h8_MODE_SELECT_ON)))
		goto err;
	mutex_unlock(&cam_mod->lock);

	return 0;
err:
	mutex_unlock(&cam_mod->lock);
	samsung_camera_module_pr_err(cam_mod, "failed with error (%d)\n",
		ret);
	return ret;
}

/*--------------------------------------------------------------------------*/

static int s5k4h8_stop_streaming(struct samsung_camera_module *cam_mod)
{
	int ret = 0, temp = 0, i;

	samsung_camera_module_pr_debug(cam_mod, "\n");

	mutex_lock(&cam_mod->lock);
	/* timing check */
	for (i = 0; i < 4; i++) {
		ret = samsung_camera_module_read_reg(cam_mod, 1, 0x0005, &temp);
		if (temp == 0xff)
			break;
		msleep(15);
		if (i == 4)
			samsung_camera_module_pr_err(cam_mod, "stream off state error\n");
	}

	if (IS_ERR_VALUE(samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA,
		s5k4h8_MODE_SELECT, s5k4h8_MODE_SELECT_OFF)))
		goto err;
	mutex_unlock(&cam_mod->lock);

	return 0;
err:
	mutex_unlock(&cam_mod->lock);
	samsung_camera_module_pr_err(cam_mod, "failed with error (%d)\n", ret);
	return ret;
}
/*--------------------------------------------------------------------------*/
/* call this function after s5k4h8 initialization
 return value: 0 update success
 1, no OTP */
int  __s5k4h8_read_otp_wb(struct samsung_camera_module *cam_mod)
{
	int ret = 0;
	int temp = 0;
	u16 r_ratio, b_ratio, gr_gain, gb_gain;

	ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A04, &temp);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"otp read failed at phase1\n");
		return ret;
	}

	otp_ptr->flag = temp;

	if (otp_ptr->flag == 0x10) {
		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A05, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->module_integrator_id = temp;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A06, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->production_year = temp;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A07, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->production_month = temp;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A08, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->production_day = temp;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A09, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->rg_ratio = (temp & 0x3) << 8;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A0A, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->rg_ratio |= temp & 0xff;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A0B, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->bg_ratio = (temp & 0x3) << 8;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A0C, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->bg_ratio |= temp & 0xff;
	} else if (otp_ptr->flag == 0xf1) {
		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A25, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->module_integrator_id = temp;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A26, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->production_year = temp;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A27, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->production_month = temp;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A28, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->production_day = temp;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A29, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->rg_ratio = (temp & 0x3) << 8;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A2A, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->rg_ratio |= temp & 0xff;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A2B, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->bg_ratio = (temp & 0x3) << 8;

		ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x0A2C, &temp);
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp read failed at phase1\n");
			return ret;
		}
		otp_ptr->bg_ratio |= temp & 0xff;
	} else if (!(otp_ptr->flag & 0x3)) {
		samsung_camera_module_pr_debug(cam_mod,
			"no valid module info and awb data in otp\n");
		otp_ptr->flag = 0;
		otp_ptr->module_integrator_id = 0;
		otp_ptr->production_year = 0;
		otp_ptr->production_month = 0;
		otp_ptr->production_day = 0;
		otp_ptr->rg_ratio = 0;
		otp_ptr->bg_ratio = 0;
		return 1;
	}

	r_ratio = 512 * (RG_Ratio_Typical) / (otp_ptr->rg_ratio);
	b_ratio = 512 * (BG_Ratio_Typical) / (otp_ptr->bg_ratio);

	if (!r_ratio || !b_ratio) {
		samsung_camera_module_pr_err(cam_mod,
			"r_ratio or b_ratio is wrong!\n");
		return 1;
	}

	if (r_ratio >= 512) {
		if (b_ratio >= 512) {
			otp_ptr->R_gain = (u16)(GAIN_DEFAULT * r_ratio / 512);
			otp_ptr->G_gain = GAIN_DEFAULT;
			otp_ptr->B_gain = (u16)(GAIN_DEFAULT * b_ratio / 512);
		} else {
			otp_ptr->R_gain = (u16)(GAIN_DEFAULT * r_ratio / b_ratio);
			otp_ptr->G_gain = (u16)(GAIN_DEFAULT * 512 / b_ratio);
			otp_ptr->B_gain = GAIN_DEFAULT;
		}
	} else {
		if (b_ratio >= 512) {
			otp_ptr->R_gain = GAIN_DEFAULT;
			otp_ptr->G_gain = (u16)(GAIN_DEFAULT * 512 / r_ratio);
			otp_ptr->B_gain = (u16)(GAIN_DEFAULT *  b_ratio / r_ratio);
		} else {
			gr_gain = (u16)(GAIN_DEFAULT * 512 / r_ratio);
			gb_gain = (u16)(GAIN_DEFAULT * 512 / b_ratio);

			if (gr_gain >= gb_gain)	{
				otp_ptr->R_gain = GAIN_DEFAULT;
				otp_ptr->G_gain = (u16)(GAIN_DEFAULT * 512 / r_ratio);
				otp_ptr->B_gain = (u16)(GAIN_DEFAULT * b_ratio / r_ratio);
			} else {
				otp_ptr->R_gain = (u16)(GAIN_DEFAULT * r_ratio / b_ratio);
				otp_ptr->G_gain = (u16)(GAIN_DEFAULT * 512 / b_ratio);
				otp_ptr->B_gain = GAIN_DEFAULT;
			}
		}
	}

	return ret;
}

int  __s5k4h8_read_otp_vcm(struct samsung_camera_module *cam_mod)
{
	int otp_flag = 0;
	int addr = 0;
	int ret = 0;
	int temp1 = 0, temp2 = 0;

	ret = samsung_camera_module_read_reg(cam_mod, 1, 0x7021, &otp_flag);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"otp vcm flag read failed\n");
		return ret;
	}
	samsung_camera_module_pr_debug(cam_mod, "otp vcm flag is %0x\n", otp_flag);

	if ((otp_flag & 0xc0) == 0x40)
		addr = 0x7022; /*set addr to group 1 base*/
	else if ((otp_flag & 0x30) == 0x10)
		addr = 0x7025; /*set addr to group 2 base*/


	if (addr != 0) {
		samsung_camera_module_pr_debug(cam_mod,
					"otp vcm addr is %0x\n", addr);
		otp_ptr->flag |= 0x20;
		ret |= samsung_camera_module_read_reg(cam_mod, 1, addr, &temp1);
		ret |= samsung_camera_module_read_reg(cam_mod, 1, (addr+2), &temp2);
		otp_ptr->VCM_start = (temp1 << 2)|(temp1 >> 6 & 0x03);
		ret |= samsung_camera_module_read_reg(cam_mod, 1, (addr+1), &temp1);
		otp_ptr->VCM_end = (temp1 << 2)+(temp2 >> 4 & 0x03);
		otp_ptr->VCM_dir = (temp2 >> 2 & 0x03);

		if (IS_ERR_VALUE(ret))
			samsung_camera_module_pr_err(cam_mod,
						"otp vcm read fail!\n");
	} else {
		samsung_camera_module_pr_debug(cam_mod,
					"no valid vcm data in otp\n");
		otp_ptr->VCM_end = 0;
		otp_ptr->VCM_end = 0;
		otp_ptr->VCM_dir = 0;
		return 1;
	}

	return ret;
}

int  __s5k4h8_read_otp_lenc(struct samsung_camera_module *cam_mod)
{
	int otp_flag = 0;
	int addr = 0;
	int ret = 0, i = 0;
	int checksum = 0;

	ret = samsung_camera_module_read_reg(cam_mod, 1, 0x7028, &otp_flag);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"otp lenc flag read failed\n");
		return ret;
	}

	samsung_camera_module_pr_debug(cam_mod,
				"otp lenc flag is 0x%0x\n", otp_flag);

	if ((otp_flag & 0xc0) == 0x40)
		addr = 0x7029; /*set addr to group 1 base*/
	else if ((otp_flag & 0x30) == 0x10)
		addr = 0x711a; /*set addr to group 2 base*/


	if (addr != 0) {
		for (i = 0; i < 240; i++) {
			ret |= samsung_camera_module_read_reg(cam_mod, 1, (addr+i),
							&(otp_ptr->lenc[i]));
			if (IS_ERR_VALUE(ret)) {
				samsung_camera_module_pr_err(cam_mod,
					"otp lenc data read failed\n");
					return ret;
			}
			checksum += otp_ptr->lenc[i];
		}

		checksum = (checksum)%255 + 1;
		ret |= samsung_camera_module_read_reg(cam_mod, 1, (addr+240),
						&(otp_ptr->checksum));
		if (IS_ERR_VALUE(ret)) {
			samsung_camera_module_pr_err(cam_mod,
				"otp lenc checksum read failed\n");
				return ret;
		}

		if (otp_ptr->checksum == checksum)
			otp_ptr->flag |= 0x10;
		else {
			samsung_camera_module_pr_err(cam_mod,
				"otp lenc checksum no match!\n");
			return 1;
		}
	} else {
		for (i = 0; i < 240; i++) {
			samsung_camera_module_pr_debug(cam_mod,
				"no valid lenc data in otp\n");
			otp_ptr->lenc[i] = 0;
		}
		return 1;
	}

	return ret;
}

static int s5k4h8_otp_read(struct samsung_camera_module *cam_mod)
{
	int ret = 0;
	int otp_ret = 0;
	struct i2c_client *client = v4l2_get_subdevdata(&cam_mod->sd);

	samsung_camera_module_pr_info(cam_mod, "\n");

	if (otp_ptr != NULL) {
		samsung_camera_module_pr_debug(cam_mod, "OTP data loaded already\n");
		return 0;
	}

	otp_ptr = kzalloc(sizeof(*otp_ptr), GFP_KERNEL);
	if (!otp_ptr) {
		samsung_camera_module_pr_err(cam_mod, "otp alloc fail!\n");
		return -ENOMEM;
	}

	ret = samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA,
		s5k4h8_MODE_SELECT, s5k4h8_MODE_SELECT_ON);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"stream on failed!\n");
		goto readotperr;
	}

	ret |= samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
		0x0A02, 0x0f);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"write 0xa02 failed!\n");
		goto readotperr;
	}

	ret |= samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
		0x0A00, 0x0100);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"write 0xa00 failed!\n");
		goto readotperr;
	}

	otp_ret = __s5k4h8_read_otp_wb(cam_mod);

	ret |= samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_TWO_BYTE_DATA,
		0x0A00, 0x0000);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"write 0xa02 failed!\n");
		goto readotperr;
	}

	ret |= samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA,
		s5k4h8_MODE_SELECT, s5k4h8_MODE_SELECT_OFF);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"stream on failed!\n");
		goto readotperr;
	}

readotperr:
	ret |= samsung_camera_module_write_reg(
		cam_mod,
		SAMSUNG_CAMERA_MODULE_REG_CONTINUE_ONE_BYTE_DATA,
		s5k4h8_MODE_SELECT, s5k4h8_MODE_SELECT_OFF);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"stream off failed!\n");
		return ret;
	}

	if (otp_ret) {
		otp_ptr->otp_en = 0;
		samsung_camera_module_pr_err(
		cam_mod,
		"get otp data failed\n");
	} else {
		otp_ptr->otp_en = 1;
		dev_info(&client->dev, "get otp data success\n");
	}

	return ret;
}

/*--------------------------------------------------------------------------*/

static int s5k4h8_check_camera_id(struct samsung_camera_module *cam_mod)
{
	u32 pidh, pidl = 0, vid = 0;
	int ret = 0;
	struct i2c_client *client;

	samsung_camera_module_pr_debug(cam_mod, "\n");

	ret |= samsung_camera_module_read_reg(cam_mod, 1, s5k4h8_PIDH_ADDR, &pidh);
	ret |= samsung_camera_module_read_reg(cam_mod, 1, s5k4h8_PIDL_ADDR, &pidl);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"register read failed, camera module powered off?while 1!\n");
		goto err;
	}

	if ((pidh == s5k4h8_PIDH_MAGIC) && (pidl == s5k4h8_PIDL_MAGIC))
		samsung_camera_module_pr_info(cam_mod,
			"successfully detected camera ID 0x%02x%02x\n",
			pidh, pidl);
	else {
		samsung_camera_module_pr_err(cam_mod,
			"wrong camera ID, expected 0x%02x%02x, detected 0x%02x%02x\n",
			s5k4h8_PIDH_MAGIC, s5k4h8_PIDL_MAGIC, pidh, pidl);
		ret = -EINVAL;
		goto err;
	}

	ret |= samsung_camera_module_read_reg(cam_mod, 1, 0x302a, &vid);
	if (IS_ERR_VALUE(ret)) {
		samsung_camera_module_pr_err(cam_mod,
			"register read failed, camera module powered off?\n");
		goto err;
	} else
		samsung_camera_module_pr_debug(cam_mod,
			"s5k4h8 chip version is 0x%2x\n", vid);

	client = v4l2_get_subdevdata(&cam_mod->sd);
	if ((vid == 0xb1) || (vid == 0xb0)) {
		s5k4h8_custom_config.configs = s5k4h8_configs;
		s5k4h8_custom_config.num_configs =
			sizeof(s5k4h8_configs)
			/ sizeof(s5k4h8_configs[0]);
		dev_info(&client->dev, "init setting for r1a\n");
	} else {
		dev_info(&client->dev, "init setting for r2a\n");
	}

	s5k4h8_filltimings(&s5k4h8_custom_config);
	cam_mod->custom = s5k4h8_custom_config;

	samsung_camera_module_pr_debug(cam_mod,
		"s5k4h8 chip version is 0x%2x,module config no. is %d\n",
		vid,
		cam_mod->custom.num_configs);
	return 0;
err:
	samsung_camera_module_pr_err(cam_mod, "failed with error (%d)\n", ret);
	return ret;
}

/* ======================================================================== */
/* This part is platform dependent */
/* ======================================================================== */

static struct v4l2_subdev_core_ops s5k4h8_camera_module_core_ops = {
	.g_ctrl = samsung_camera_module_g_ctrl,
	.s_ctrl = samsung_camera_module_s_ctrl,
	.s_ext_ctrls = samsung_camera_module_s_ext_ctrls,
	.s_power = samsung_camera_module_s_power,
	.ioctl = samsung_camera_module_ioctl
};

static struct v4l2_subdev_video_ops s5k4h8_camera_module_video_ops = {
	.enum_frameintervals = samsung_camera_module_enum_frameintervals,
	.s_mbus_fmt = samsung_camera_module_s_fmt,
	.g_mbus_fmt = samsung_camera_module_g_fmt,
	.try_mbus_fmt = samsung_camera_module_try_fmt,
	.s_frame_interval = samsung_camera_module_s_frame_interval,
	.s_stream = samsung_camera_module_s_stream
};

static struct v4l2_subdev_ops s5k4h8_camera_module_ops = {
	.core = &s5k4h8_camera_module_core_ops,
	.video = &s5k4h8_camera_module_video_ops
};

static struct samsung_camera_module_custom_config s5k4h8_custom_config = {
	.start_streaming = s5k4h8_start_streaming,
	.stop_streaming = s5k4h8_stop_streaming,
	.s_ctrl = s5k4h8_s_ctrl,
	.s_ext_ctrls = s5k4h8_s_ext_ctrls,
	.g_ctrl = s5k4h8_g_ctrl,
	.g_timings = s5k4h8_g_timings,
	.check_camera_id = s5k4h8_check_camera_id,
	.read_otp = s5k4h8_otp_read,
	.configs = s5k4h8_configs,
	.num_configs = sizeof(s5k4h8_configs) / sizeof(s5k4h8_configs[0]),
	.power_up_delays_ms = {5, 20, 0},
	/*
	*0: Exposure time valid fileds;
	*1: Exposure gain valid fileds;
	*(2 fileds == 1 frames)
	*/
	.exposure_valid_frame = {4, 4}
};

static int s5k4h8_probe(
	struct i2c_client *client,
	const struct i2c_device_id *id)
{
	dev_info(&client->dev, "probing...\n");

	s5k4h8_filltimings(&s5k4h8_custom_config);
	v4l2_i2c_subdev_init(&s5k4h8.sd, client, &s5k4h8_camera_module_ops);
	s5k4h8.sd.flags |= V4L2_SUBDEV_FL_HAS_DEVNODE;
	s5k4h8.custom = s5k4h8_custom_config;

	mutex_init(&s5k4h8.lock);
	dev_info(&client->dev, "probing successful\n");

	return 0;
}

static int s5k4h8_remove(struct i2c_client *client)
{
	struct samsung_camera_module *cam_mod = i2c_get_clientdata(client);

	dev_info(&client->dev, "removing device...\n");

	if (!client->adapter)
		return -ENODEV;	/* our client isn't attached */

	mutex_destroy(&cam_mod->lock);
	samsung_camera_module_release(cam_mod);

	if (otp_ptr != NULL)
		kfree(otp_ptr);
	dev_info(&client->dev, "removed\n");
	return 0;
}

static const struct i2c_device_id s5k4h8_id[] = {
	{ s5k4h8_DRIVER_NAME, 0 },
	{ }
};

static struct of_device_id s5k4h8_of_match[] = {
	{.compatible = "samsung,s5k4h8-v4l2-i2c-subdev"},
	{},
};

MODULE_DEVICE_TABLE(i2c, s5k4h8_id);

static struct i2c_driver s5k4h8_i2c_driver = {
	.driver = {
		.name = s5k4h8_DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table = s5k4h8_of_match
	},
	.probe = s5k4h8_probe,
	.remove = s5k4h8_remove,
	.id_table = s5k4h8_id,
};

module_i2c_driver(s5k4h8_i2c_driver);

MODULE_DESCRIPTION("SoC Camera driver for s5k4h8");
MODULE_AUTHOR("George");
MODULE_LICENSE("GPL");
